Dev/test 2
sunjoo-org/search-orchestration-demo pull request #4
Opened 2022-01-26 02:49 UTC by sunjoo-park

2

2022-01-26 02:51 UTC, sunjoo-park commented
test comment

2022-01-26 02:52 UTC, sunjoo-park commented
start build

2022-01-26 02:54 UTC, sunjoo-park reviewed
test

2022-01-26 02:54 UTC, sunjoo-park commented on Jenkinsfile
>                  if(env.CHANGE_ID) {
Check if this is pull request

2022-01-26 03:14 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/6/

2022-01-26 03:14 UTC, sunjoo-park commented
Post Section

2022-01-26 05:09 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/8/

2022-01-26 05:09 UTC, sunjoo-park commented
Post Section

2022-01-26 05:10 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/9/

2022-01-26 05:10 UTC, sunjoo-park commented
Post Section

2022-01-26 05:17 UTC, all4dich commented
test

2022-01-26 05:18 UTC, all4dich approved these changes

2022-01-26 05:44 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/11/

2022-01-26 05:44 UTC, sunjoo-park commented
Post Section

2022-01-26 08:00 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/test-org/job/search-orchestration-demo/job/PR-4/1/

2022-01-26 08:00 UTC, sunjoo-park commented
Post Section

2022-01-26 08:38 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/12/

2022-01-26 08:38 UTC, sunjoo-park commented
Post Section

2022-01-26 08:43 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/nota-github/job/search-orchestration-demo/job/PR-4/1/

2022-01-26 08:43 UTC, sunjoo-park commented
Ttes Commenv http://8779-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/13/

2022-01-26 08:43 UTC, sunjoo-park commented
Post Section

2022-01-26 08:43 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/test-org/job/search-orchestration-demo/job/PR-4/2/

2022-01-26 08:43 UTC, sunjoo-park commented
Post Section

2022-01-26 08:43 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/1/

2022-01-26 08:43 UTC, sunjoo-park commented
Post Section

2022-01-26 08:43 UTC, sunjoo-park commented
Post Section

2022-01-26 08:43 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/test-repo/job/PR-4/1/

2022-01-26 08:43 UTC, sunjoo-park commented
Post Section

2022-01-26 08:51 UTC, sunjoo-park reviewed
test

2022-01-26 08:55 UTC, all4dich approved these changes
test 2

2022-01-27 14:42 UTC, all4dich approved these changes
test 2

2022-01-27 14:44 UTC, all4dich reviewed
test - comment

2022-01-27 14:45 UTC, all4dich requested changes, later dismissed
test - request change

2022-01-27 14:58 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/nota-github/job/search-orchestration-demo/job/PR-4/2/

2022-01-27 14:58 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/2/

2022-01-27 14:58 UTC, sunjoo-park commented
Post Section

2022-01-27 14:58 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/test-org/job/search-orchestration-demo/job/PR-4/3/

2022-01-27 14:58 UTC, sunjoo-park commented
Post Section

2022-01-27 14:58 UTC, sunjoo-park commented
Post Section

2022-01-27 14:58 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/test-repo/job/PR-4/2/

2022-01-27 14:58 UTC, sunjoo-park commented
Post Section

2022-01-27 15:01 UTC, sunjoo-park reviewed
1123123

2022-01-27 15:04 UTC, all4dich reviewed
test - PENDING

2022-01-27 15:06 UTC, all4dich reviewed
test - other comment

2022-01-27 15:06 UTC, all4dich approved these changes

2022-01-27 15:10 UTC, all4dich requested changes
test - queust asdf

2022-01-27 15:11 UTC, all4dich approved these changes
test - Approve

2022-01-28 01:21 UTC, all4dich reviewed
test - start build

2022-01-28 01:23 UTC, all4dich reviewed
test - start build

2022-01-28 01:24 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/4/

2022-01-28 01:24 UTC, sunjoo-park commented
Post Section

2022-01-28 01:25 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/5/

2022-01-28 01:25 UTC, sunjoo-park commented
Post Section

2022-01-28 01:27 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/3/

2022-01-28 01:27 UTC, sunjoo-park commented
Post Section

2022-01-28 01:27 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/6/

2022-01-28 01:27 UTC, sunjoo-park commented
Post Section

2022-01-28 01:27 UTC, all4dich reviewed
test - start build

2022-01-28 01:29 UTC, all4dich commented
start build

2022-01-28 01:29 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/4/

2022-01-28 01:29 UTC, sunjoo-park commented
Post Section

2022-01-28 01:29 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/7/

2022-01-28 01:29 UTC, sunjoo-park commented
Post Section

2022-01-28 01:29 UTC, all4dich reviewed
test - start build again

2022-01-28 01:30 UTC, all4dich reviewed
test - start build again

2022-01-28 01:30 UTC, all4dich reviewed
start build

2022-01-28 01:34 UTC, all4dich commented
start build

2022-01-28 01:35 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/5/

2022-01-28 01:35 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/8/

2022-01-28 01:35 UTC, sunjoo-park commented
Post Section

2022-01-28 01:35 UTC, sunjoo-park commented
Post Section

2022-01-28 01:42 UTC, all4dich reviewed
start

2022-01-28 01:46 UTC, all4dich commented
start build

2022-01-28 01:47 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/6/

2022-01-28 01:47 UTC, sunjoo-park commented
Post Section

2022-01-28 01:47 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/9/

2022-01-28 01:47 UTC, sunjoo-park commented
Post Section

2022-01-28 01:51 UTC, all4dich commented
start build

2022-01-28 01:51 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/10/

2022-01-28 01:51 UTC, sunjoo-park commented
Post Section

2022-01-28 01:51 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/7/

2022-01-28 01:51 UTC, sunjoo-park commented
Post Section

2022-01-28 02:14 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/11/

2022-01-28 02:14 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:14 UTC, sunjoo-park commented
Post Section

2022-01-28 02:14 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/8/

2022-01-28 02:14 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:14 UTC, sunjoo-park commented
Post Section

2022-01-28 02:14 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/9/

2022-01-28 02:14 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:14 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/12/

2022-01-28 02:14 UTC, sunjoo-park commented
Post Section

2022-01-28 02:14 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/10/

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/11/

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/13/

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/12/

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/14/

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/13/

2022-01-28 02:15 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/15/

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
start build from Pipeline

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:15 UTC, sunjoo-park commented
Post Section

2022-01-28 02:16 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/16/

2022-01-28 02:16 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/14/

2022-01-28 02:16 UTC, sunjoo-park commented
Post Section

2022-01-28 02:16 UTC, sunjoo-park commented
Post Section

2022-01-28 02:16 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/15/

2022-01-28 02:16 UTC, sunjoo-park commented
Post Section

2022-01-28 02:16 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/17/

2022-01-28 02:16 UTC, sunjoo-park commented
Post Section

2022-01-28 02:18 UTC, all4dich commented
start build

2022-01-28 02:18 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/16/

2022-01-28 02:18 UTC, sunjoo-park commented
Post Section

2022-01-28 02:18 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/18/

2022-01-28 02:18 UTC, sunjoo-park commented
Post Section

2022-01-28 02:23 UTC, all4dich approved these changes
test - Approve

2022-01-28 02:28 UTC, sunjoo-park commented
Ttes Commenv http://ec2-52-78-168-231.ap-northeast-2.compute.amazonaws.com:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/17/

2022-01-28 02:28 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/19/

2022-01-28 02:28 UTC, sunjoo-park commented
Post Section

2022-01-28 02:28 UTC, sunjoo-park commented
Post Section

2022-01-28 02:34 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/20/

2022-01-28 02:35 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/21/

2022-01-28 02:36 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/22/

2022-01-28 03:51 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/14/

2022-01-28 03:51 UTC, sunjoo-park commented
Post Section

2022-01-28 04:00 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/23/

2022-01-28 04:00 UTC, sunjoo-park commented
Post Section

2022-01-28 04:00 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/15/

2022-01-28 04:00 UTC, sunjoo-park commented
Post Section

2022-01-28 04:01 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/16/

2022-01-28 04:01 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/24/

2022-01-28 04:01 UTC, sunjoo-park commented
Post Section

2022-01-28 04:01 UTC, sunjoo-park commented
Post Section

2022-01-28 04:02 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/17/

2022-01-28 04:02 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/25/

2022-01-28 04:02 UTC, sunjoo-park commented
Post Section

2022-01-28 04:02 UTC, sunjoo-park commented
Post Section

2022-01-28 04:04 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/18/

2022-01-28 04:04 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/26/

2022-01-28 04:04 UTC, sunjoo-park commented
Post Section

2022-01-28 04:04 UTC, sunjoo-park commented
Post Section

2022-01-28 04:12 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/28/

2022-01-28 04:12 UTC, sunjoo-park commented
start build

2022-01-28 04:12 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/20/

2022-01-28 04:12 UTC, sunjoo-park commented
Post Section

2022-01-28 04:12 UTC, sunjoo-park commented
start build

2022-01-28 04:12 UTC, sunjoo-park commented
Post Section

2022-01-28 04:12 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/29/

2022-01-28 04:12 UTC, sunjoo-park commented
start build

2022-01-28 04:12 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/21/

2022-01-28 04:12 UTC, sunjoo-park commented
start build

2022-01-28 04:12 UTC, sunjoo-park commented
Post Section

2022-01-28 04:12 UTC, sunjoo-park commented
Post Section

2022-01-28 04:12 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/30/

2022-01-28 04:12 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/22/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/31/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/23/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/32/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/33/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/24/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/25/

2022-01-28 04:13 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/34/

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
start build

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:13 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/26/

2022-01-28 04:14 UTC, sunjoo-park commented
start build

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/35/

2022-01-28 04:14 UTC, sunjoo-park commented
start build

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/36/

2022-01-28 04:14 UTC, sunjoo-park commented
${message}

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/27/

2022-01-28 04:14 UTC, sunjoo-park commented
${message}

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/28/

2022-01-28 04:14 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/37/

2022-01-28 04:14 UTC, sunjoo-park commented
${message}

2022-01-28 04:14 UTC, sunjoo-park commented
${message}

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:14 UTC, sunjoo-park commented
Post Section

2022-01-28 04:15 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/38/

2022-01-28 04:15 UTC, sunjoo-park commented
comment by Jenkinspipeline

2022-01-28 04:15 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/29/

2022-01-28 04:15 UTC, sunjoo-park commented
Post Section

2022-01-28 04:15 UTC, sunjoo-park commented
comment by Jenkinspipeline

2022-01-28 04:16 UTC, sunjoo-park commented
Post Section

2022-01-28 04:22 UTC, sunjoo-park commented
Ttes Commenv https://d0bf-61-82-106-164.jp.ngrok.io/job/z-experiment/job/demo-repo/job/PR-4/30/

2022-01-28 04:26 UTC, sunjoo-park commented
Ttes Commenv http://61.82.106.164:7070/job/z-experiment/job/sunjoo-org/job/search-orchestration-demo/job/PR-4/39/

2022-01-28 04:26 UTC, sunjoo-park commented
comment by Jenkinspipeline

2022-01-28 04:27 UTC, sunjoo-park commented
Post Section

2022-01-28 04:27 UTC, merged